devcontainers

diff --git a/.github/workflows/docker-test.yml b/.github/workflows/docker-test.yml
--- a/.github/workflows/docker-test.yml
+++ b/.github/workflows/docker-test.yml
@@ -23,10 +23,30 @@ jobs:
           docker-compose -f docker-compose.yml build
           docker-compose -f docker-compose.yml up -d
 
-      - name: Wait for application to be ready
-        run: |
-          echo "Waiting for application to be ready..."
-          timeout 300 bash -c 'while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' localhost:8000)" != "200" ]]; do sleep 5; done' || false
+      - name: Check Docker containers and wait for application
+            run: |
+              echo "Checking Docker containers..."
+              docker-compose -f docker-compose.yml ps
+              
+              echo "Checking logs of the app container..."
+              docker-compose -f docker-compose.yml logs app
+              
+              echo "Waiting for application to be ready..."
+              attempt_counter=0
+              max_attempts=30
+              
+              until $(curl --output /dev/null --silent --head --fail http://localhost:8000); do
+                  if [ ${attempt_counter} -eq ${max_attempts} ];then
+                    echo "Max attempts reached. Application failed to start."
+                    exit 1
+                  fi
+                  
+                  printf '.'
+                  attempt_counter=$(($attempt_counter+1))
+                  sleep 10
+              done
+              
+              echo "Application is up and running!"
 
       # - name: Run Laravel migrations
       #   run: docker-compose -f docker-compose.yml exec -T app php artisan migrate
